import torch
import os
from transformers import AutoModelForCausalLM, AutoTokenizer
from trl import DPOTrainer, DPOConfig
from datasets import load_dataset

# --- 0. Script Preamble and Prerequisites ---
print("--- DPO Training Script ---")
print("Prerequisites:")
print("1. Ensure `custom_dpo_data.jsonl` exists (generated by `prepare_custom_data.py` or your custom script).")
print("2. This script is intended for an environment with suitable GPU resources (e.g., NVIDIA Ampere or newer for BF16).")
print("3. Required libraries (transformers, trl, datasets, torch, accelerate) should be installed.")
print("-" * 30)

# --- 1. Define Model and Data Parameters ---
model_id = "google/gemma-3-4b-it"  # Using a smaller Gemma model for demonstration
dataset_path = "custom_dpo_data.jsonl" # Output of prepare_custom_data.py
output_directory_base = "~/gemma3-4b-dpo-finetuned"
output_directory = os.path.expanduser(output_directory_base)

print(f"Model ID: {model_id}")
print(f"Dataset Path: {dataset_path}")
print(f"Output Directory: {output_directory}")

# --- 2. Load Model and Tokenizer ---
print("\n--- Loading Model and Tokenizer ---")
model = None
tokenizer = None

try:
    print(f"Loading model: {model_id}...")
    # For resource-constrained environments, one might consider:
    # model = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype=torch.bfloat16, device_map="auto")
    # However, for script completeness, we'll load it normally first.
    # Device_map="auto" might be needed for larger models if not using accelerate's default handling.
    model = AutoModelForCausalLM.from_pretrained(model_id)
    print("Model loaded successfully.")

    print(f"Loading tokenizer for: {model_id}...")
    tokenizer = AutoTokenizer.from_pretrained(model_id)
    print("Tokenizer loaded successfully.")

    # Set pad_token if it's not already set (common for GPT-like models)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
        print("tokenizer.pad_token set to tokenizer.eos_token")

except OSError as e:
    print(f"OSError: Could not load model or tokenizer. Check model_id, network, or disk space: {e}")
    exit()
except Exception as e:
    print(f"An unexpected error occurred during model/tokenizer loading: {e}")
    exit()

# --- 3. Load and Prepare Dataset ---
print("\n--- Loading and Preparing Dataset ---")
try:
    # Load the dataset from the JSONL file
    # The DPO trainer expects columns "prompt", "chosen", and "rejected"
    train_dataset = load_dataset("json", data_files=dataset_path, split="train")
    print(f"Dataset loaded successfully from {dataset_path}")
    print(f"Number of samples: {len(train_dataset)}")
    print(f"First sample: {train_dataset[0] if len(train_dataset) > 0 else 'Dataset is empty'}")
except FileNotFoundError:
    print(f"ERROR: Dataset file not found at {dataset_path}. Please generate it first using prepare_custom_data.py.")
    exit()
except Exception as e:
    print(f"An unexpected error occurred while loading the dataset: {e}")
    exit()

# --- 4. Initialize DPOConfig ---
print("\n--- Initializing DPOConfig ---")
try:
    training_args = DPOConfig(
        output_dir=output_directory,
        num_train_epochs=1,                   # Keep low for demonstration; adjust for real training
        per_device_train_batch_size=1,        # Adjust based on GPU memory
        gradient_accumulation_steps=4,        # Effective batch size = 1 * 4 = 4
        learning_rate=5e-5,
        logging_steps=10,
        save_steps=100,                       # Save checkpoints less frequently for quick test
        bf16=True,                            # Set to True if your hardware supports bfloat16 (Ampere+ GPUs)
                                              # Set to False or use fp16=True if bf16 is not supported.
        # fp16=False, # Uncomment and set to True if using fp16 instead of bf16
        max_prompt_length=512,                # Max length of the prompt
        max_length=1024,                      # Max total length (prompt + chosen/rejected response)
        report_to="none",                     # "tensorboard", "wandb", or "none". Set to "none" for simple local runs.
        # beta=0.1, # Default DPO beta parameter
        # remove_unused_columns=False # Important if your dataset has other columns you use in formatting_func
    )
    print("DPOConfig initialized successfully.")
    print(f"Output directory: {training_args.output_dir}")
    print(f"BF16 enabled: {training_args.bf16}")
    if training_args.bf16 and not torch.cuda.is_bf16_supported():
        print("WARNING: BF16 is set to True, but current hardware may not support it. Training might fail or fall back.")
except Exception as e:
    print(f"An unexpected error occurred while initializing DPOConfig: {e}")
    exit()

# --- 5. Initialize DPOTrainer ---
print("\n--- Initializing DPOTrainer ---")
# Note: The DPOTrainer will internally create a reference model (ref_model)
# by copying the provided model if `ref_model` is None. This is memory-intensive.
# For very large models, you might load the ref_model separately, potentially in a lower precision
# or on CPU if memory is extremely constrained, though this can impact training dynamics.
try:
    trainer = DPOTrainer(
        model=model,
        ref_model=None,  # DPOTrainer will handle creating a reference model copy
        args=training_args,
        train_dataset=train_dataset,
        tokenizer=tokenizer,
        # peft_config=peft_config, # Uncomment if using PEFT for LoRA, etc.
        # formatting_func=formatting_prompts_func, # Uncomment if you need custom data formatting
    )
    print("DPOTrainer initialized successfully.")
except Exception as e:
    print(f"An unexpected error occurred while initializing DPOTrainer: {e}")
    print("This could be due to OOM if the model is large and a reference copy is being made.")
    exit()

# --- 6. Start Training ---
print("\n--- Starting DPO Training (Simulated/Short) ---")
print("Note: Actual training can take a significant amount of time and resources.")
print("This script might run a very short training or skip it in a constrained environment.")

try:
    # To prevent long runs in CI/CD or limited environments,
    # you might add a condition to skip or limit training steps:
    # if "CI" in os.environ or "SUBTASK_ENV" in os.environ:
    #     print("Simulated training run: Not executing trainer.train() in this environment.")
    #     # Create dummy output for the next steps
    #     if not os.path.exists(training_args.output_dir):
    #         os.makedirs(training_args.output_dir)
    # else:
    #     trainer.train() # Full training
    # For this subtask, we assume it's okay to call train() and it will be handled by the environment
    # (e.g., by being very short or interrupted if too long)
    
    # Let's modify DPOConfig for a minimal run for testing purposes
    # This ensures the script is runnable end-to-end even if it does very little actual training.
    trainer.args.max_steps = 2 # Override for a very short run
    trainer.args.save_steps = 1 # Save after 1 step for testing save
    trainer.args.logging_steps = 1
    print(f"Overriding training to max_steps={trainer.args.max_steps} for quick test.")

    training_results = trainer.train()
    print("Training completed (or simulated completion).")
    print(f"Training results: {training_results}")

except Exception as e:
    print(f"An error occurred during training: {e}")
    # Even if training fails, try to proceed if it's an OOM or similar resource issue
    # and some progress might have been made or for cleanup.
    # However, for a critical error, exiting might be better.
    # For now, we'll just print and continue to saving if possible.

# --- 7. Save Model and Tokenizer (Post-Training) ---
print("\n--- Saving Model and Tokenizer ---")
try:
    print(f"Saving model to {training_args.output_dir}...")
    trainer.save_model()  # Saves the fine-tuned model
    print("Model saved successfully.")

    print(f"Saving tokenizer to {training_args.output_dir}...")
    tokenizer.save_pretrained(training_args.output_dir)
    print("Tokenizer saved successfully.")
except Exception as e:
    print(f"An error occurred while saving the model or tokenizer: {e}")

print("\n--- DPO Training Script Finished ---")
print(f"Final model and tokenizer should be in: {training_args.output_dir}")
print("Remember to adapt `num_train_epochs`, `max_steps`, batch sizes, and other parameters for actual training runs.")
